<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Afney.Cad.Mechanical\Afney.Cad.Mechanical.csproj" />
    <ProjectReference Include="..\..\src\Afney.Cad.Domain\Afney.Cad.Domain.csproj" />
    <ProjectReference Include="..\..\src\Afney.Cad.Geometry\Afney.Cad.Geometry.csproj" />
    <ProjectReference Include="..\..\src\Afney.Cad.Application\Afney.Cad.Application.csproj" />
    <ProjectReference Include="..\..\src\Afney.Cad.Database\Afney.Cad.Database.csproj" />
    <ProjectReference Include="..\..\src\Afney.Cad.Commands\Afney.Cad.Commands.csproj" />
    <ProjectReference Include="..\..\src\Afney.Cad.Infrastructure\Afney.Cad.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Afney.Cad.SpatialIndex\Afney.Cad.SpatialIndex.csproj" />
  </ItemGroup>

</Project>
