<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Afney.Cad.Commands\Afney.Cad.Commands.csproj" />
    <ProjectReference Include="..\Afney.Cad.Mechanical\Afney.Cad.Mechanical.csproj" />
    <ProjectReference Include="..\Afney.Cad.Database\Afney.Cad.Database.csproj" />
    <ProjectReference Include="..\Afney.Cad.Render\Afney.Cad.Render.csproj" />
    <ProjectReference Include="..\Afney.Cad.SpatialIndex\Afney.Cad.SpatialIndex.csproj" />
    <!-- Geometry references are transitive usually, but CadEngine uses Primitives directly -->
    <ProjectReference Include="..\Afney.Cad.Geometry\Afney.Cad.Geometry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ACadSharp" Version="3.4.2" />
    <PackageReference Include="Serilog" Version="3.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

</Project>
