<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Afney.Cad.Database\Afney.Cad.Database.csproj" />
    <ProjectReference Include="..\Afney.Cad.Domain\Afney.Cad.Domain.csproj" />
    <ProjectReference Include="..\Afney.Cad.Mechanical\Afney.Cad.Mechanical.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

</Project>
